on: release
name: Build and Publish Release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.1
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: "Build darwin/amd64"
      run: env GOOS=darwin GOARCH=amd64 go build -v -o godoc2ghmd_darwin_amd64 .

    - name: "Build linux/amd64"
      run: env GOOS=linux GOARCH=amd64 go build -v -o godoc2ghmd_linux_amd64 .

    - name: "Build windows/amd64"
      run: env GOOS=windows GOARCH=amd64 go build -v -o godoc2ghmd_windows_amd64 .

    - name: Upload binaries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'godoc2ghmd_*_amd64'
